
trigger:
- master
 
jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: |
        sudo apt-get update
        sudo apt-get install libsdl2-dev
        git submodule update --init
        cmake --version
        mkdir build
        cd build
        cmake -DBUILD_NUMBER=$(Build.BuildId) -DCI_PROVIDER="AzureDevOps" -G"Unix Makefiles" ..
        make -j4
- job: macOS
  pool:
    vmImage: 'macOS-latest'
  steps:
  - script: |
        brew install sdl2
        git submodule update --init
        cmake --version
        mkdir build
        cd build
        cmake -DBUILD_NUMBER=$(Build.BuildId) -DCI_PROVIDER="AzureDevOps" -G"Unix Makefiles" ..
        make -j4
- job: Windows64
  pool:
    vmImage: 'windows-2019'
  steps:
  - script: |
        git submodule update --init
        mkdir C:\temp
        powershell Invoke-WebRequest 'https://github.com/AliveTeam/SDL2_win32_dev_mirror/files/8710940/SDL2-devel-2.0.22-VC.zip' -OutFile C:\temp\SDL2-devel-2.0.22-VC.zip
        7z x C:\Temp\SDL2-devel-2.0.22-VC.zip -oC:\Temp
        mkdir build
        cd build
        cmake .. -DBUILD_NUMBER=$(Build.BuildId) -DCI_PROVIDER="AzureDevOps" -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DSDL2_DIR=C:\Temp\SDL2-2.0.22 -G "Visual Studio 16 2019" -A x64
        cmake --build .
